site_name: LIS/ICT 690 - AI Literacy for Information Organizations
site_url: https://heng-zheng.github.io/ai-literacy/

plugins:
  - search

nav:
  - Home: index.md
  - _auto:
      # BEGIN AUTO NAV
      Weeks:
        Week 01: weeks/week-01.md
        Week 02: weeks/week-02.md
        Week 03: weeks/week-03.md
        Week 04: weeks/week-04.md
        Week 05: weeks/week-05.md
        Week 06: weeks/week-06.md
        Week 07: weeks/week-07.md
        Week 08: weeks/week-08.md
        Week 09: weeks/week-09.md
        Week 10: weeks/week-10.md
        Week 11: weeks/week-11.md
        Week 12: weeks/week-12.md
        Week 13: weeks/week-13.md
      Concepts:
        Ai Definition: concepts/ai-definition.md
        Ai Ethics: concepts/ai-ethics.md
        AI Paradigms: concepts/ai-paradigms.md
        Ai Timeline: concepts/ai-timeline.md
        Copyright Tdm: concepts/copyright-tdm.md
        Symbolic Ai: concepts/symbolic-ai.md
      # END AUTO NAV


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest

extra_css:
  - stylesheets/extra.css